// Package claudetui provides the claude TUI harness implementing
// harnesses.Harness over one lifecycle-contained PTY per invocation, with
// hook-based progress events and transcript-derived final output. It proves
// subscription-mode billing for cost-based routing without retaining live
// Claude state between invocations. It also implements PortableRuntimeHarness,
// delegating the shared Claude Code binary and state closure to
// internal/harnesses/anthropic while retaining its distinct PTY identity and
// environment boundary. Operator CLAUDE_* variables and locale/terminal names
// are its inherited portable namespace; ANTHROPIC_* is excluded, while HOME,
// PATH, USER, LOGNAME, SHELL, and XDG path variables are regenerated by guest
// activation rather than inherited from the preparing host.
//
// CONTRACT-004 invariant #2 forbids this package from importing
// internal/harnesses/claude; shared code must flow through
// internal/harnesses/anthropic.
package claudetui
