package gemini

import (
	"bytes"
	"encoding/json"
	"errors"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/easel/fizeau/internal/harnesses"
	"github.com/easel/fizeau/internal/safefs"
)

const (
	geminiPortableNoRelaunchEnvironment = "GEMINI_CLI_NO_RELAUNCH"
	geminiPortableMaxSettingsBytes      = 8 << 20
)

var geminiPortableFixedArguments = []string{"--ignore-env"}

var geminiPortableFixedOptionValues = []harnesses.PortableRuntimeFixedOptionValue{
	{Option: "-e", Value: "none"},
}

var geminiPortableUnsetEnvironmentNames = []string{
	"BROWSER", "CLOUD_SHELL", "EDITOR", "GEMINI_CLI_HOME",
	"GEMINI_CLI_IDE_SERVER_STDIO_ARGS", "GEMINI_CLI_IDE_SERVER_STDIO_COMMAND",
	"GEMINI_CLI_SYSTEM_DEFAULTS_PATH", "GEMINI_CLI_SYSTEM_SETTINGS_PATH",
	"GEMINI_CLI_TRUSTED_FOLDERS_PATH", "LD_AUDIT", "LD_LIBRARY_PATH",
	"LD_PRELOAD", "NODE_OPTIONS", "NODE_PATH", "VISUAL",
}

// geminiPortableExecutionConstraints closes every Gemini configuration source
// that cannot be represented by the exact portable state projection. HOME is
// already generated by activation; unsetting GEMINI_CLI_HOME keeps that
// generated baseline authoritative instead of accepting an ambient override.
func geminiPortableExecutionConstraints() harnesses.PortableRuntimeExecutionConstraints {
	constraints := harnesses.PortableRuntimeExecutionConstraints{
		Environment: []harnesses.PortableRuntimeEnvironmentConstraint{
			{Name: geminiPortableNoRelaunchEnvironment, Kind: harnesses.PortableRuntimeEnvironmentFixedTrue},
			{Name: "GEMINI_CLI_HOME", Kind: harnesses.PortableRuntimeEnvironmentUnset},
			{Name: "GEMINI_CLI_SYSTEM_DEFAULTS_PATH", Kind: harnesses.PortableRuntimeEnvironmentGuestPath, GuestPath: harnesses.PortableRuntimeGuestPath{Scope: harnesses.PortableRuntimeGuestPathTmp, Target: "gemini/system-defaults.json"}},
			{Name: "GEMINI_CLI_SYSTEM_SETTINGS_PATH", Kind: harnesses.PortableRuntimeEnvironmentGuestPath, GuestPath: harnesses.PortableRuntimeGuestPath{Scope: harnesses.PortableRuntimeGuestPathTmp, Target: "gemini/settings.json"}},
			{Name: "GEMINI_CLI_TRUSTED_FOLDERS_PATH", Kind: harnesses.PortableRuntimeEnvironmentGuestPath, GuestPath: harnesses.PortableRuntimeGuestPath{Scope: harnesses.PortableRuntimeGuestPathTmp, Target: "gemini/trusted-folders.json"}},
		},
		RequiredAbsentPaths: []harnesses.PortableRuntimeGuestPath{
			{Scope: harnesses.PortableRuntimeGuestPathHome, Target: ".agents/skills"},
			{Scope: harnesses.PortableRuntimeGuestPathHome, Target: ".env"},
			{Scope: harnesses.PortableRuntimeGuestPathHome, Target: ".gemini/.env"},
			{Scope: harnesses.PortableRuntimeGuestPathHome, Target: ".gemini/GEMINI.md"},
			{Scope: harnesses.PortableRuntimeGuestPathHome, Target: ".gemini/agents"},
			{Scope: harnesses.PortableRuntimeGuestPathHome, Target: ".gemini/commands"},
			{Scope: harnesses.PortableRuntimeGuestPathHome, Target: ".gemini/extensions"},
			{Scope: harnesses.PortableRuntimeGuestPathHome, Target: ".gemini/policies"},
			{Scope: harnesses.PortableRuntimeGuestPathHome, Target: ".gemini/skills"},
			{Scope: harnesses.PortableRuntimeGuestPathHome, Target: ".gemini/trustedFolders.json"},
		},
		FixedArguments:    append([]string(nil), geminiPortableFixedArguments...),
		FixedOptionValues: append([]harnesses.PortableRuntimeFixedOptionValue(nil), geminiPortableFixedOptionValues...),
	}
	for _, name := range []string{
		"BROWSER", "CLOUD_SHELL", "EDITOR", "GEMINI_CLI_IDE_SERVER_STDIO_ARGS",
		"GEMINI_CLI_IDE_SERVER_STDIO_COMMAND", "LD_AUDIT", "LD_LIBRARY_PATH",
		"LD_PRELOAD", "NODE_OPTIONS", "NODE_PATH", "VISUAL",
	} {
		constraints.Environment = append(constraints.Environment, harnesses.PortableRuntimeEnvironmentConstraint{
			Name: name,
			Kind: harnesses.PortableRuntimeEnvironmentUnset,
		})
	}
	return constraints
}

func geminiPortableArguments(base []string, req harnesses.ExecuteRequest, promptMode string) ([]string, error) {
	if err := validateGeminiPortableLaterArguments(base); err != nil {
		return nil, err
	}
	args := append([]string(nil), geminiPortableFixedArguments...)
	for _, pair := range geminiPortableFixedOptionValues {
		args = append(args, pair.Option, pair.Value)
	}
	args = append(args, base...)
	if req.Model != "" {
		args = append(args, "-m", req.Model)
	}
	switch req.Permissions {
	case "", "safe":
		args = append(args, "--approval-mode", "plan")
	case "supervised":
		args = append(args, "--approval-mode", "default")
	case "unrestricted":
		args = append(args, "--approval-mode", "yolo")
	}
	if value := harnesses.AdapterReasoningValue(req); value != "" {
		return nil, geminiPortableRuntimeError("reasoning control is unsupported")
	}
	switch promptMode {
	case "arg":
		args = append(args, "-p", req.Prompt)
	case "stdin":
		args = append(args, "-p", "")
	default:
		return nil, geminiPortableRuntimeError("prompt delivery mode is unsupported")
	}
	return args, nil
}

func validateGeminiPortableLaterArguments(arguments []string) error {
	for _, argument := range arguments {
		if geminiPortableConflictingArgument(argument) {
			return geminiPortableRuntimeError("configured arguments conflict with fixed execution controls")
		}
		if geminiPortableExternalConfigurationArgument(argument) {
			return geminiPortableRuntimeError("configured arguments declare external configuration")
		}
	}
	return nil
}

func geminiPortableConflictingArgument(argument string) bool {
	key := argument
	if index := strings.IndexByte(key, '='); index >= 0 {
		key = key[:index]
	}
	if key == "-e" || key == "-l" || key == "--extensions" || key == "--list-extensions" || key == "--ignore-env" {
		return true
	}
	return (strings.HasPrefix(key, "-e") || strings.HasPrefix(key, "-l")) && len(key) > 2
}

func geminiPortableExternalConfigurationArgument(argument string) bool {
	key := argument
	if index := strings.IndexByte(key, '='); index >= 0 {
		key = key[:index]
	}
	switch key {
	case "--admin-policy", "--include-directories", "--policy":
		return true
	default:
		return false
	}
}

func geminiPortableRunnerEnvironment(environment []string) []string {
	result := make([]string, 0, len(environment)+1)
	prefix := geminiPortableNoRelaunchEnvironment + "="
	unset := make(map[string]struct{}, len(geminiPortableUnsetEnvironmentNames))
	for _, name := range geminiPortableUnsetEnvironmentNames {
		unset[name] = struct{}{}
	}
	for _, assignment := range environment {
		name := assignment
		if index := strings.IndexByte(name, '='); index >= 0 {
			name = name[:index]
		}
		if name == geminiPortableNoRelaunchEnvironment {
			continue
		}
		if _, remove := unset[name]; remove {
			continue
		}
		result = append(result, assignment)
	}
	return append(result, prefix+"true")
}

// inspectGeminiPortableUserConfiguration validates the exact settings and
// executable-source boundary before either ordinary dispatch or portable
// state discovery may use it.
func inspectGeminiPortableUserConfiguration(home string) error {
	if !filepath.IsAbs(home) || filepath.Clean(home) != home {
		return geminiPortableRuntimeError("generated-home source is invalid")
	}
	root := filepath.Join(home, ".gemini")
	data, present, err := readGeminiPortableOptionalSettings(filepath.Join(root, "settings.json"))
	if err != nil {
		return err
	}
	if present {
		if err := validateGeminiPortableSettings(data); err != nil {
			return err
		}
	}
	for _, source := range []string{
		filepath.Join(home, ".env"),
		filepath.Join(root, ".env"),
		filepath.Join(root, "GEMINI.md"),
		filepath.Join(root, "agents"),
		filepath.Join(root, "commands"),
		filepath.Join(root, "extensions"),
		filepath.Join(root, "policies"),
		filepath.Join(root, "skills"),
	} {
		present, err := geminiPortablePathExists(source)
		if err != nil {
			return geminiPortableRuntimeError("user configuration cannot be inspected")
		}
		if present {
			return geminiPortableRuntimeError("user configuration declares an executable source")
		}
	}
	return nil
}

func inspectGeminiPortableProjectSources(workDir string) error {
	root := workDir
	if root == "" {
		var err error
		root, err = os.Getwd()
		if err != nil {
			return geminiPortableRuntimeError("project configuration cannot be inspected")
		}
	}
	absolute, err := filepath.Abs(root)
	if err != nil {
		return geminiPortableRuntimeError("project configuration cannot be inspected")
	}
	project := filepath.Clean(absolute)
	boundary, err := geminiPortableProjectBoundary(project)
	if err != nil {
		return err
	}
	for current := project; ; current = filepath.Dir(current) {
		for _, relative := range []string{".env", ".gemini", filepath.Join(".agents", "skills"), "GEMINI.md"} {
			present, pathErr := geminiPortablePathExists(filepath.Join(current, relative))
			if pathErr != nil {
				return geminiPortableRuntimeError("project configuration cannot be inspected")
			}
			if present {
				return geminiPortableRuntimeError("project configuration declares an ambient source")
			}
		}
		if current == boundary {
			return nil
		}
	}
}

// geminiPortableProjectBoundary returns the nearest Git worktree root. When
// no worktree marker exists, WorkDir itself is the only project-owned root;
// unrelated temporary-directory and home ancestors are not project sources.
func geminiPortableProjectBoundary(project string) (string, error) {
	for current := project; ; current = filepath.Dir(current) {
		present, err := geminiPortablePathExists(filepath.Join(current, ".git"))
		if err != nil {
			return "", geminiPortableRuntimeError("project boundary cannot be inspected")
		}
		if present {
			return current, nil
		}
		parent := filepath.Dir(current)
		if parent == current {
			return project, nil
		}
	}
}

func inspectGeminiPortableSystemSources(paths []string) error {
	for _, name := range []string{
		"GEMINI_CLI_HOME", "GEMINI_CLI_SYSTEM_DEFAULTS_PATH",
		"GEMINI_CLI_SYSTEM_SETTINGS_PATH", "GEMINI_CLI_TRUSTED_FOLDERS_PATH",
	} {
		if value, exists := os.LookupEnv(name); exists && value != "" {
			return geminiPortableRuntimeError("ambient environment names an external configuration source")
		}
	}
	for _, path := range paths {
		present, err := geminiPortablePathExists(path)
		if err != nil {
			return geminiPortableRuntimeError("system configuration cannot be inspected")
		}
		if present {
			return geminiPortableRuntimeError("system configuration declares an ambient source")
		}
	}
	return nil
}

func geminiPortableDefaultSystemSources() []string {
	return []string{
		"/etc/gemini-cli/settings.json",
		"/etc/gemini-cli/system-defaults.json",
		"/etc/gemini-cli/policies",
	}
}

func validateGeminiPortableSettings(data []byte) error {
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.UseNumber()
	var document map[string]any
	if err := decoder.Decode(&document); err != nil || document == nil {
		return geminiPortableRuntimeError("settings document is invalid")
	}
	if err := decoder.Decode(&struct{}{}); !errors.Is(err, io.EOF) {
		return geminiPortableRuntimeError("settings document is invalid")
	}
	if geminiPortableSettingsContainExecutableSource(nil, document) {
		return geminiPortableRuntimeError("settings document declares an executable or external source")
	}
	return nil
}

func geminiPortableSettingsContainExecutableSource(path []string, value any) bool {
	switch typed := value.(type) {
	case map[string]any:
		for key, child := range typed {
			if geminiPortableForbiddenSetting(path, key) {
				return true
			}
			if geminiPortableSettingsContainExecutableSource(append(path, key), child) {
				return true
			}
		}
	case []any:
		for _, child := range typed {
			if geminiPortableSettingsContainExecutableSource(path, child) {
				return true
			}
		}
	}
	return false
}

func geminiPortableForbiddenSetting(path []string, key string) bool {
	normalized := strings.ToLower(strings.NewReplacer("-", "", "_", "").Replace(key))
	switch normalized {
	case "adminpolicypaths", "agents", "browser", "browserhelpers", "command", "commands",
		"extensions", "hooks", "hooksconfig", "mcp", "mcpservers", "policypaths", "skills",
		"systemdefaultspath", "systemsettingspath":
		return true
	}
	if strings.HasSuffix(normalized, "command") || strings.HasSuffix(normalized, "commands") {
		return true
	}
	if len(path) == 0 || !strings.EqualFold(path[0], "context") {
		return false
	}
	switch normalized {
	case "customignorefilepaths", "filename", "includedirectories", "loadmemoryfromincludedirectories",
		"memoryboundarymarkers":
		return true
	default:
		return false
	}
}

func readGeminiPortableOptionalSettings(path string) ([]byte, bool, error) {
	present, err := geminiPortablePathExists(path)
	if err != nil || !present {
		return nil, present, err
	}
	info, err := os.Lstat(path)
	if err != nil || !info.Mode().IsRegular() || info.Mode()&os.ModeSymlink != 0 || info.Mode().Perm()&0o111 != 0 {
		return nil, true, geminiPortableRuntimeError("settings source has an unsupported file type")
	}
	file, err := safefs.OpenRead(path)
	if err != nil {
		return nil, true, geminiPortableRuntimeError("settings source cannot be read")
	}
	data, readErr := io.ReadAll(io.LimitReader(file, geminiPortableMaxSettingsBytes+1))
	closeErr := file.Close()
	if readErr != nil || closeErr != nil || len(data) > geminiPortableMaxSettingsBytes {
		return nil, true, geminiPortableRuntimeError("settings source cannot be read")
	}
	return data, true, nil
}

func geminiPortablePathExists(path string) (bool, error) {
	_, err := os.Lstat(path)
	if err == nil {
		return true, nil
	}
	if errors.Is(err, os.ErrNotExist) {
		return false, nil
	}
	return false, err
}
