#!/usr/bin/env bash
#
# gate-e-aggregate.sh
#
# Aggregates the 6 per-run verdicts produced by gate-e-billing-observation.sh
# (3 pty + 3 print) and applies the campaign decision rule from
# docs/helix/02-design/billing-observation-claude-tui.md §Overall verdict.
#
#   accepted     : >= 5 runs subscription-confirmed AND no subscription-rejected
#   rejected     : any run subscription-rejected
#   inconclusive : >= 1 subscription-ambiguous AND no subscription-rejected
#
# USAGE
#   bash scripts/gate-e-aggregate.sh [VERDICTDIR]
#     VERDICTDIR : dir holding run-*.json (default: $VERDICTDIR env or /tmp/gate-e-verdicts)
#
# Writes a Markdown verdict report to $VERDICTDIR/gate-e-verdict.md and prints the
# overall outcome on stdout. Exit code: 0 accepted, 1 rejected, 2 inconclusive.
#
set -uo pipefail

VERDICTDIR="${1:-${VERDICTDIR:-/tmp/gate-e-verdicts}}"
REPORT="$VERDICTDIR/gate-e-verdict.md"

if [[ ! -d "$VERDICTDIR" ]]; then
  echo "error: VERDICTDIR '$VERDICTDIR' does not exist (run gate-e-billing-observation.sh first)" >&2
  exit 3
fi

# Pull a top-level string/number field out of a run verdict JSON without jq.
json_field() {
  local file="$1" key="$2"
  grep -oE "\"$key\"[[:space:]]*:[[:space:]]*(\"[^\"]*\"|-?[0-9]+|null)" "$file" 2>/dev/null \
    | head -1 | sed -E "s/.*:[[:space:]]*//; s/^\"//; s/\"$//"
}

confirmed=0
rejected=0
ambiguous=0
missing=0
rows=""

for transport in pty print; do
  for run in 1 2 3; do
    f="$VERDICTDIR/run-${transport}-${run}.json"
    if [[ ! -f "$f" ]]; then
      missing=$(( missing + 1 ))
      rows+="| $transport | $run | (missing) | - | - | - | run verdict file not found |"$'\n'
      continue
    fi
    v="$(json_field "$f" verdict)"
    bb="$(json_field "$f" billing_mode_before)"
    ba="$(json_field "$f" billing_mode_after)"
    delta="$(json_field "$f" delta_messages)"
    notes="$(json_field "$f" notes)"
    case "$v" in
      subscription-confirmed) confirmed=$(( confirmed + 1 ));;
      subscription-rejected)  rejected=$(( rejected + 1 ));;
      subscription-ambiguous) ambiguous=$(( ambiguous + 1 ));;
    esac
    rows+="| $transport | $run | $v | ${bb:-?} | ${ba:-?} | ${delta:-?} | ${notes:-} |"$'\n'
  done
done

# Decision rule.
if [[ "$rejected" -gt 0 ]]; then
  OVERALL="rejected"
  EXIT=1
elif [[ "$missing" -gt 0 || "$ambiguous" -gt 0 ]]; then
  OVERALL="inconclusive"
  EXIT=2
elif [[ "$confirmed" -ge 5 ]]; then
  OVERALL="accepted"
  EXIT=0
else
  OVERALL="inconclusive"
  EXIT=2
fi

{
  echo "# Gate-E Billing-Observation Verdict"
  echo
  echo "_Generated by scripts/gate-e-aggregate.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)_"
  echo
  echo "Methodology: docs/helix/02-design/billing-observation-claude-tui.md"
  echo "Verdict source dir: \`$VERDICTDIR\`"
  echo
  echo "## Per-Run Results"
  echo
  echo "| Transport | Run | Verdict | Billing Before | Billing After | Δ messages | Notes |"
  echo "|-----------|-----|---------|----------------|---------------|------------|-------|"
  printf '%s' "$rows"
  echo
  echo "## Tally"
  echo
  echo "| Outcome | Count |"
  echo "|---------|-------|"
  echo "| subscription-confirmed | $confirmed |"
  echo "| subscription-rejected  | $rejected |"
  echo "| subscription-ambiguous | $ambiguous |"
  echo "| missing run files      | $missing |"
  echo
  echo "## Overall Verdict: **$OVERALL**"
  echo
  echo "Decision rule applied:"
  echo "- \`accepted\` if >= 5 confirmed and no rejected and no missing/ambiguous"
  echo "- \`rejected\` if any run rejected"
  echo "- \`inconclusive\` if >= 1 ambiguous/missing and no rejected"
  echo
  echo "## Operator Attestation (fill in by hand)"
  echo
  echo "- [ ] Single Claude account in use; no concurrent Claude sessions during any measurement window."
  echo "- [ ] Subscription valid for >= 7 days beyond the measurement window."
  echo "- [ ] \`claude\` binary version: \`<record output of 'claude --version'>\`"
  echo "- [ ] Concurrent-activity windows reviewed and confirmed clean:"
  echo "  - pty run 1: <start>–<end>"
  echo "  - pty run 2: <start>–<end>"
  echo "  - pty run 3: <start>–<end>"
  echo "  - print run 1: <start>–<end>"
  echo "  - print run 2: <start>–<end>"
  echo "  - print run 3: <start>–<end>"
} > "$REPORT"

echo "==> overall verdict: $OVERALL (confirmed=$confirmed rejected=$rejected ambiguous=$ambiguous missing=$missing)"
echo "==> wrote $REPORT"
exit "$EXIT"
